// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: paginator/paginator.payload.proto

package paginator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchMode int32

const (
	SearchMode_SEARCH_MODE_UNSPECIFIED       SearchMode = 0
	SearchMode_SEARCH_MODE_CONTAINS          SearchMode = 1
	SearchMode_SEARCH_MODE_PREFIX            SearchMode = 2
	SearchMode_SEARCH_MODE_FULL_TEXT         SearchMode = 3
	SearchMode_SEARCH_MODE_TRIGRAM           SearchMode = 4
	SearchMode_SEARCH_MODE_FULL_TEXT_TRIGRAM SearchMode = 5
)

// Enum value maps for SearchMode.
var (
	SearchMode_name = map[int32]string{
		0: "SEARCH_MODE_UNSPECIFIED",
		1: "SEARCH_MODE_CONTAINS",
		2: "SEARCH_MODE_PREFIX",
		3: "SEARCH_MODE_FULL_TEXT",
		4: "SEARCH_MODE_TRIGRAM",
		5: "SEARCH_MODE_FULL_TEXT_TRIGRAM",
	}
	SearchMode_value = map[string]int32{
		"SEARCH_MODE_UNSPECIFIED":       0,
		"SEARCH_MODE_CONTAINS":          1,
		"SEARCH_MODE_PREFIX":            2,
		"SEARCH_MODE_FULL_TEXT":         3,
		"SEARCH_MODE_TRIGRAM":           4,
		"SEARCH_MODE_FULL_TEXT_TRIGRAM": 5,
	}
)

func (x SearchMode) Enum() *SearchMode {
	p := new(SearchMode)
	*p = x
	return p
}

func (x SearchMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchMode) Descriptor() protoreflect.EnumDescriptor {
	return file_paginator_paginator_payload_proto_enumTypes[0].Descriptor()
}

func (SearchMode) Type() protoreflect.EnumType {
	return &file_paginator_paginator_payload_proto_enumTypes[0]
}

func (x SearchMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchMode.Descriptor instead.
func (SearchMode) EnumDescriptor() ([]byte, []int) {
	return file_paginator_paginator_payload_proto_rawDescGZIP(), []int{0}
}

type PageQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Fields        []string               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Sort          []*Sort                `protobuf:"bytes,4,rep,name=sort,proto3" json:"sort,omitempty"`
	Search        *Search                `protobuf:"bytes,5,opt,name=search,proto3" json:"search,omitempty"`
	LastId        string                 `protobuf:"bytes,6,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageQuery) Reset() {
	*x = PageQuery{}
	mi := &file_paginator_paginator_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageQuery) ProtoMessage() {}

func (x *PageQuery) ProtoReflect() protoreflect.Message {
	mi := &file_paginator_paginator_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageQuery.ProtoReflect.Descriptor instead.
func (*PageQuery) Descriptor() ([]byte, []int) {
	return file_paginator_paginator_payload_proto_rawDescGZIP(), []int{0}
}

func (x *PageQuery) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageQuery) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PageQuery) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *PageQuery) GetSort() []*Sort {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *PageQuery) GetSearch() *Search {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *PageQuery) GetLastId() string {
	if x != nil {
		return x.LastId
	}
	return ""
}

type PageMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	HasNext       bool                   `protobuf:"varint,5,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	HasPrev       bool                   `protobuf:"varint,6,opt,name=has_prev,json=hasPrev,proto3" json:"has_prev,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageMeta) Reset() {
	*x = PageMeta{}
	mi := &file_paginator_paginator_payload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageMeta) ProtoMessage() {}

func (x *PageMeta) ProtoReflect() protoreflect.Message {
	mi := &file_paginator_paginator_payload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageMeta.ProtoReflect.Descriptor instead.
func (*PageMeta) Descriptor() ([]byte, []int) {
	return file_paginator_paginator_payload_proto_rawDescGZIP(), []int{1}
}

func (x *PageMeta) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageMeta) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PageMeta) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageMeta) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *PageMeta) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *PageMeta) GetHasPrev() bool {
	if x != nil {
		return x.HasPrev
	}
	return false
}

type Sort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Desc          bool                   `protobuf:"varint,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sort) Reset() {
	*x = Sort{}
	mi := &file_paginator_paginator_payload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sort) ProtoMessage() {}

func (x *Sort) ProtoReflect() protoreflect.Message {
	mi := &file_paginator_paginator_payload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sort.ProtoReflect.Descriptor instead.
func (*Sort) Descriptor() ([]byte, []int) {
	return file_paginator_paginator_payload_proto_rawDescGZIP(), []int{2}
}

func (x *Sort) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Sort) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

type Search struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []string               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Mode          SearchMode             `protobuf:"varint,3,opt,name=mode,proto3,enum=paginator.SearchMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Search) Reset() {
	*x = Search{}
	mi := &file_paginator_paginator_payload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Search) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search) ProtoMessage() {}

func (x *Search) ProtoReflect() protoreflect.Message {
	mi := &file_paginator_paginator_payload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search.ProtoReflect.Descriptor instead.
func (*Search) Descriptor() ([]byte, []int) {
	return file_paginator_paginator_payload_proto_rawDescGZIP(), []int{3}
}

func (x *Search) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Search) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *Search) GetMode() SearchMode {
	if x != nil {
		return x.Mode
	}
	return SearchMode_SEARCH_MODE_UNSPECIFIED
}

var File_paginator_paginator_payload_proto protoreflect.FileDescriptor

const file_paginator_paginator_payload_proto_rawDesc = "" +
	"\n" +
	"!paginator/paginator.payload.proto\x12\tpaginator\"\xb6\x01\n" +
	"\tPageQuery\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\x12#\n" +
	"\x04sort\x18\x04 \x03(\v2\x0f.paginator.SortR\x04sort\x12)\n" +
	"\x06search\x18\x05 \x01(\v2\x11.paginator.SearchR\x06search\x12\x17\n" +
	"\alast_id\x18\x06 \x01(\tR\x06lastId\"\xa1\x01\n" +
	"\bPageMeta\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\x12\x19\n" +
	"\bhas_next\x18\x05 \x01(\bR\ahasNext\x12\x19\n" +
	"\bhas_prev\x18\x06 \x01(\bR\ahasPrev\"0\n" +
	"\x04Sort\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\bR\x04desc\"e\n" +
	"\x06Search\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fields\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12)\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x15.paginator.SearchModeR\x04mode*\xb2\x01\n" +
	"\n" +
	"SearchMode\x12\x1b\n" +
	"\x17SEARCH_MODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SEARCH_MODE_CONTAINS\x10\x01\x12\x16\n" +
	"\x12SEARCH_MODE_PREFIX\x10\x02\x12\x19\n" +
	"\x15SEARCH_MODE_FULL_TEXT\x10\x03\x12\x17\n" +
	"\x13SEARCH_MODE_TRIGRAM\x10\x04\x12!\n" +
	"\x1dSEARCH_MODE_FULL_TEXT_TRIGRAM\x10\x05B/Z-github.com/siti-nabila/grpc-auth/pb/paginatorb\x06proto3"

var (
	file_paginator_paginator_payload_proto_rawDescOnce sync.Once
	file_paginator_paginator_payload_proto_rawDescData []byte
)

func file_paginator_paginator_payload_proto_rawDescGZIP() []byte {
	file_paginator_paginator_payload_proto_rawDescOnce.Do(func() {
		file_paginator_paginator_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paginator_paginator_payload_proto_rawDesc), len(file_paginator_paginator_payload_proto_rawDesc)))
	})
	return file_paginator_paginator_payload_proto_rawDescData
}

var file_paginator_paginator_payload_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_paginator_paginator_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_paginator_paginator_payload_proto_goTypes = []any{
	(SearchMode)(0),   // 0: paginator.SearchMode
	(*PageQuery)(nil), // 1: paginator.PageQuery
	(*PageMeta)(nil),  // 2: paginator.PageMeta
	(*Sort)(nil),      // 3: paginator.Sort
	(*Search)(nil),    // 4: paginator.Search
}
var file_paginator_paginator_payload_proto_depIdxs = []int32{
	3, // 0: paginator.PageQuery.sort:type_name -> paginator.Sort
	4, // 1: paginator.PageQuery.search:type_name -> paginator.Search
	0, // 2: paginator.Search.mode:type_name -> paginator.SearchMode
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_paginator_paginator_payload_proto_init() }
func file_paginator_paginator_payload_proto_init() {
	if File_paginator_paginator_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paginator_paginator_payload_proto_rawDesc), len(file_paginator_paginator_payload_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_paginator_paginator_payload_proto_goTypes,
		DependencyIndexes: file_paginator_paginator_payload_proto_depIdxs,
		EnumInfos:         file_paginator_paginator_payload_proto_enumTypes,
		MessageInfos:      file_paginator_paginator_payload_proto_msgTypes,
	}.Build()
	File_paginator_paginator_payload_proto = out.File
	file_paginator_paginator_payload_proto_goTypes = nil
	file_paginator_paginator_payload_proto_depIdxs = nil
}
