// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.2
// source: user/user.service.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_user_service_proto protoreflect.FileDescriptor

const file_user_user_service_proto_rawDesc = "" +
	"\n" +
	"\x17user/user.service.proto\x12\x04user\x1a\x17user/user.payload.proto2z\n" +
	"\vUserService\x126\n" +
	"\bRegister\x12\x11.user.AuthRequest\x1a\x17.user.UserTokenResponse\x123\n" +
	"\x05Login\x12\x11.user.AuthRequest\x1a\x17.user.UserTokenResponseB*Z(github.com/siti-nabila/grpc-auth/pb/userb\x06proto3"

var file_user_user_service_proto_goTypes = []any{
	(*AuthRequest)(nil),       // 0: user.AuthRequest
	(*UserTokenResponse)(nil), // 1: user.UserTokenResponse
}
var file_user_user_service_proto_depIdxs = []int32{
	0, // 0: user.UserService.Register:input_type -> user.AuthRequest
	0, // 1: user.UserService.Login:input_type -> user.AuthRequest
	1, // 2: user.UserService.Register:output_type -> user.UserTokenResponse
	1, // 3: user.UserService.Login:output_type -> user.UserTokenResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_user_service_proto_init() }
func file_user_user_service_proto_init() {
	if File_user_user_service_proto != nil {
		return
	}
	file_user_user_payload_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_service_proto_rawDesc), len(file_user_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_user_service_proto_goTypes,
		DependencyIndexes: file_user_user_service_proto_depIdxs,
	}.Build()
	File_user_user_service_proto = out.File
	file_user_user_service_proto_goTypes = nil
	file_user_user_service_proto_depIdxs = nil
}
